name: Deployment

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install
          npm install gh-pages --save-dev

      - name: Build
        run: npm run build

      - name: Deploy
        run: gh-pages -d build
