name: Deployment

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git remote set-url origin https://bhavinpanchani:~Ashokbhai007@github.com/bhavinpanchani/portfolio.git
          npm run deploy
        env:
          user_name: 'bhavinpanchani'
          password: '~Ashokbhai007'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}

#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: npm ci, build and test
#         run: |
#           npm ci
#           npm run build --if-present
# #          npm test
#       - name: deploy to gh-pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
# #           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#           publish_dir: ./build   
